language: node_js
node_js:
- 10.16.3
script:
- npm run build
- npm run test
branches:
  only:
  - master
notifications:
  slack:
    secure: pnHVWnofOtwXCwYwjnBe2/tAyqWWgzWr4CvMYPtq7V3PVauZyqkpO/3T3Pvk3A6O0hAWmA5bGr0GnKzTPV6hTbFLNo8yYL9YyFZH726mAQbsjEFQBJWI7/mQF30Rh37Ma1OJ45/6mvJ+YDa2BWRy4wjmnhPB07xhX70BRDq0S83mvzZMP2Ux0MDnIdA6tv7psDUB8ZNPtWgUQZQrjnfoKF9+NKtt5rNCBdfNQyap5WwYyAFPB537IoMlUsaJpMcLSxjfE4HQtcnYXFSQJIKB56A72GTpMql/9fxO6MldjznNIMN49XkyZJkaIU9gsOXDh7U0qb2rcQm/5Rtpx8V/8o3SyWnwpT3rhyz9CgDYXyI2u0Y9l5vh66VBPynwv5tZVg5OlqdkIzch/vANo5yiNydpW02X0lnjmNHjfIGq7W5RvGeWUi26k0Dw/j9XkyEc06Fdfvdbwyqi6Iizv7y6soPSg9QEP485QFfED3NwZNZkA5ziFLoOssgxgroMiMj/cBqcBTGjGfunIPAbPiSsg8Yhnk4O98OowLTM7VItAwfsp9b4EIa/Rl0aVHIJF70QxanW9GVugnLMojYfVPu3gK3kbZm+If504nSjC2KYSxOXcMryzPnALeLBdKRfgk7WsSkbnEvoZrRFicC7ISpiGGOzBEOA76Lgp+mQ7OemqKg=
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: JRUUP8mS+n8TavPg7y0UNZx/XPeNu7X1b/LPXj3OnlPB3MTO77wVU3jgunlwVMh+R7i6zdVQzTsTwkModgY10s9+y6ml7GFtyRKqif2CFMoY+78yBMhl9j6mJr+ENCh+Mlkjm0rfZ9RSpjJFM1zRF2/e3C0xERiIRlMH0r2Z4dATXlJjH78+cCPWSWC51yRlk5WjEiqvkmo+rcJaWGU6jmDotPhcX4KvpXGjhw6e3/2VvimZc/hJZhBWUFRnAUDkEGoVIPz96M9z0u6OFR6Srs+SD6q3FEDHJuWb8XLMSpALZRoyQ0uEQGvJmP3wvAmTe1GPoxZS0Wu9xwnrme3tUgf9BBOG5IUTYSrl6S3utHlmk7Ko/a6uC2qRbI1LkMAu5absQT1rcEXJ4E4jO82ZziWgGwkTFWcnG8IVcosPr6/bY613J4CJ9GmKOSLLxgpkOcS9qMjCtP5rABXibe0nfb7RpKDgy5bbdm0XxpLR7tD4DvsGXF2hiDbz5lp9KuicVNrHp3N0UgvOjtFD/ZQXPf5cZ3bVRQNfowZQlAZmlXRINjt+5qmNUNpVN6CavlahWaIBA2e15/XO/7bT9yC54HwotgVuXOkdHNxwiCyvpixKuAIkVicvHgsQ3m/SWD1lWLyBtqYTG1Iy6aEnEo0SdJ7hqzPyBro4UdxkdoyxZng=
env:
  global:
    secure: GDrmxB9Kjq84/rpP965FB8PQNS+JOb/VCnAFcCiKKVV0TDcXK9lUdKTeWqDqzFkIGHRU687vBGaL4BnxYGivNm1eglniu8hCoL92E2HNIQ3s5kIDg0GzZMDLj/uk/QzfB5m8m9aYpKXjf7fNR7ABYT9ZCmpzDnvjL5cU7lVHzIyU84xC27xbJT5uAO/YPJib3wCMhYBgY0z5QJ7vaVk2mbOGHbfaodcJkDk3+k/pA0RtZCWem9Y3p5juSnuHeMVm0aiyZ1+vw26g+RtvP1pGwMHMqi2dZs9y602uDetEX/WAeGRGfNGv6K21uJ91ILfj3RGe1S5hgjVgtLeOduxowk1m1m4xYv01IAYbRCcP6Ksq5gRyRYWU25HuGU4ePddpwCSMD6OYuANcfKPSYaFpSw+LIKah9PVp6eNSXlhueb/xJY9blfICSMyLcbYX8s2H6iPLYPuI0sIrEH5G1Goha/QDo7cPN17IV8opwdZbk3E8VHoMDOaUDMhn0qBdSq1CZoIwpoSreVieBbiIBCq2NHWhSwgscBYFTjMn7jQ4YS9JuLrtT7KC8XpHgYix+KVpfMbtPH8/0h/HWZTarZ3xMD8MyZjK4jQwNNHb+dfVOgTWFrrUtQhRZA2UW5owxhbDvs248ubjEMuwFrHk8aikHB1hJBCiAHfNsgI9+vAd0SU=
